### PR TITLE
Style patch

### PR DESCRIPTION
**Pull request by diepoe**
This PR does following:

- adding prism for syntax highlighting at the markdown for the docs and the blog
- adding the Roboto font where needed.

### CODE REVIEW

**Comment by softmarshmallow** [comment]
LGTM

**Comment by diepoe** [comment]
I just wanted get feedback on my idea of using the fira code font for the code blocks (live demo can be found [here](https://sveltesociety.dev/cheatsheet))

**Comment by softmarshmallow** [comment]
> I just wanted get feedback on my idea of using the fira code font for the code blocks (live demo can be found [here](https://sveltesociety.dev/cheatsheet))

Seems like very suiting font for code blocks. I'll Update the designs too.
(Actually i was looking for something like this.)
One concern might be the font loading performance - since ony in docs it uses almost 3 fontfaces. (this could be optimized later)

Let's go with it

Ref: https://github.com/tonsky/FiraCode

**Comment by diepoe** [comment]
> > I just wanted get feedback on my idea of using the fira code font for the code blocks (live demo can be found [here](https://sveltesociety.dev/cheatsheet))
> 
> Seems like very suiting font for code blocks. I'll Update the designs too.
> (Actually i was looking for something like this.)
> One concern might be the font loading performance - since ony in docs it uses almost 3 fontfaces. (this could be optimized later)
> 
> Let's go with it
> 
> Ref: https://github.com/tonsky/FiraCode

I just would import the font file or isn't that a good practice 🤔

**Comment by softmarshmallow** [comment]
> > > I just wanted get feedback on my idea of using the fira code font for the code blocks (live demo can be found [here](https://sveltesociety.dev/cheatsheet))
> 
> > 
> 
> > Seems like very suiting font for code blocks. I'll Update the designs too.
> 
> > (Actually i was looking for something like this.)
> 
> > One concern might be the font loading performance - since ony in docs it uses almost 3 fontfaces. (this could be optimized later)
> 
> > 
> 
> > Let's go with it
> 
> > 
> 
> > Ref: https://github.com/tonsky/FiraCode
> 
> 
> 
> I just would import the font file or isn't that a good practice 🤔

I think it'll be just fine

**Pull request merged**
