### PR TITLE
setup blog and smaller adjustments

### PR DESCRIPTION
**Pull request by diepoe**
I just setup the blog with mdx and made some smaller (style) corrections. This isn’t perfect (f.e. I’ll create another layout for a mdx-blogpost in the future) but it’s working 🙂.

### CODE REVIEW

**Comment by GwonHeeJun** [comment]
in my opinion, header is a global component, What do you think about moving the header from wrapper to _app.js?

**Comment by diepoe** [comment]
@GwonHeeJun Oh yeah, good idea, let me push a fix 👍🏻

**Comment by GwonHeeJun** [comment]
Good! 😎 😎

**Comment by diepoe** [comment]
Fixed 👍🏻

**Comment by diepoe** [comment]
When you forget hitting `Comment` after writing a comment 🙈

**Comment by GwonHeeJun** [comment]
> Fixed 👍🏻

Good! Confirm please @softmarshmallow

**Comment by softmarshmallow** [comment]
LGTM

**Pull request merged**
