### PR TITLE
Add code font and other styling

### PR DESCRIPTION
**Pull request by diepoe**
This add's the FiraCode font for the code blocks and the code labels. It also underlined the links at documentation entrys and the blogposts.

### CODE REVIEW

**Comment by softmarshmallow** [comment]
https://user-images.githubusercontent.com/16307013/111065343-800ea300-84fc-11eb-9a4a-1daf3cb63b4b.mov

I'm not quick sure this commit causes this, but the page viewport seems to be needed to be fixed.

And always, thanks for your contribution 😀

**Comment by diepoe** [comment]
Oh ok

**Comment by diepoe** [comment]
Oh yeah I see

**Comment by diepoe** [comment]
Should be fixed now @softmarshmallow

**Review by softmarshmallow — APPROVED** [review]

**Pull request merged**
